security:
    encoders:
        Integrated\Bundle\UserBundle\Model\User: sha512

    providers:
        integrated_user:
            id: integrated_user.security.provider

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt|configurator)|css|images|js)/
            security:   false

        default:
            pattern:  ^/
            anonymous: ~
            form_login:
                csrf_provider: form.csrf_provider

                login_path:    integrated_user_login
                check_path:    integrated_user_check

            logout:
                path:   integrated_user_logout
                target: /

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_REMEMBERED }
